### ISSUE TITLE
Cannot run demo

### ISSUE THREAD

**Issue by davidbrochart** [willmcgugan/textual-markdown#1]
After installing in a fresh environment, `python -m textual_markdown demo.md` fails with:
```pytb
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/david/mambaforge/envs/foo/lib/python3.11/site-packages/textual_markdown/__main__.py", line 9, in <module>
    app.run()
  File "/home/david/mambaforge/envs/foo/lib/python3.11/site-packages/textual/app.py", line 864, in run
    asyncio.run(run_app())
  File "/home/david/mambaforge/envs/foo/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/home/david/mambaforge/envs/foo/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/david/mambaforge/envs/foo/lib/python3.11/asyncio/base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/david/mambaforge/envs/foo/lib/python3.11/site-packages/textual/app.py", line 856, in run_app
    await self.run_async(
  File "/home/david/mambaforge/envs/foo/lib/python3.11/site-packages/textual/app.py", line 831, in run_async
    await app._shutdown()
  File "/home/david/mambaforge/envs/foo/lib/python3.11/site-packages/textual/app.py", line 1634, in _shutdown
    await self._close_all()
  File "/home/david/mambaforge/envs/foo/lib/python3.11/site-packages/textual/app.py", line 1614, in _close_all
    await self._prune_node(screen)
  File "/home/david/mambaforge/envs/foo/lib/python3.11/site-packages/textual/app.py", line 2037, in _prune_node
    await asyncio.gather(*close_messages)
  File "/home/david/mambaforge/envs/foo/lib/python3.11/site-packages/textual/message_pump.py", line 301, in _close_messages
    await self._task
  File "/home/david/mambaforge/envs/foo/lib/python3.11/site-packages/textual/message_pump.py", line 311, in _process_messages
    await self._pre_process()
  File "/home/david/mambaforge/envs/foo/lib/python3.11/site-packages/textual/message_pump.py", line 327, in _pre_process
    await self._dispatch_message(events.Compose(sender=self))
  File "/home/david/mambaforge/envs/foo/lib/python3.11/site-packages/textual/message_pump.py", line 403, in _dispatch_message
    await self.on_event(message)
  File "/home/david/mambaforge/envs/foo/lib/python3.11/site-packages/textual/message_pump.py", line 431, in on_event
    await self._on_message(event)
  File "/home/david/mambaforge/envs/foo/lib/python3.11/site-packages/textual/message_pump.py", line 452, in _on_message
    await invoke(method, message)
  File "/home/david/mambaforge/envs/foo/lib/python3.11/site-packages/textual/_callback.py", line 28, in invoke
    result = await result
             ^^^^^^^^^^^^
  File "/home/david/mambaforge/envs/foo/lib/python3.11/site-packages/textual/widget.py", line 2329, in _on_compose
    await self.mount(*widgets)
          ^^^^^^^^^^^^^^^^^^^^
  File "/home/david/mambaforge/envs/foo/lib/python3.11/site-packages/textual/widget.py", line 599, in mount
    self.app._register(
  File "/home/david/mambaforge/envs/foo/lib/python3.11/site-packages/textual/app.py", line 1565, in _register
    apply_stylesheet(widget)
  File "/home/david/mambaforge/envs/foo/lib/python3.11/site-packages/textual/css/stylesheet.py", line 378, in apply
    rules = reversed(self.rules)
                     ^^^^^^^^^^
  File "/home/david/mambaforge/envs/foo/lib/python3.11/site-packages/textual/css/stylesheet.py", line 149, in rules
    self.parse()
  File "/home/david/mambaforge/envs/foo/lib/python3.11/site-packages/textual/css/stylesheet.py", line 313, in parse
    raise StylesheetParseError(error_renderable)
textual.css.stylesheet.StylesheetParseError: <textual.css.stylesheet.StylesheetErrors object at 0x7f5a55c7f610>
```

**Comment by willmcgugan** [comment]
Ah, it needs a Textual updated. 

Hold off for now.

**Comment by willmcgugan** [comment]
Ok, try updating now...

**Comment by davidbrochart** [comment]
It works, thanks!
